[package]
name = "zipstream"
version = "0.1.0"
authors = ["Kevin Mehall <kevin.mehall@3drobotics.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
futures = "0.1.25"
bytes = "0.4.10"
regex = "1.0.5"
tokio-io = "0.1"
tokio-fs = "0.1"
hyper = "0.12.17"
hyper-tls = "0.3.1"
rusoto_s3 = "0.35.0"
rusoto_core = "0.35.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
log = "0.4.6"
log-panics = "2.0.0"
env_logger = "0.6.0"
clap = "2"
lazy_static = "1.1.0"
chrono = { version = "0.4", features = ["serde"] }
